### ISSUE TITLE
[Feature Request]: Pixtral 8-bit

### ISSUE THREAD

**Issue by Vigilence** [SeanScripts/ComfyUI-PixtralLlamaVision#2]
https://huggingface.co/DewEfresh/pixtral-12b-8bit/tree/main

**Comment by SeanScripts** [comment]
I was able to run this model without issues. It will require a GPU with 24 GB of VRAM. It runs at about 2.3 tokens per second on a 4090. I'm not sure whether the difference in quality is worth the slower speed compared to the NF4 version.

It seems to have much better performance on OCR than the NF4 version (which seems to completely break down if the image is mostly text), though it took a few attempts for me to get it to follow the instruction compared to Llama Vision.

![pixtral_8bit_ocr_example](https://github.com/user-attachments/assets/57cc656a-695a-463d-9acd-8df85ea3aed3)

(Example was from this article: https://www.e2enetworks.com/blog/a-guide-to-building-ocr-systems-using-pixtral-12b -- I have no association with them, just wanted to see an example of someone using Pixtral for OCR. And the 8-bit model still seems to have some degradation on this task compared to FP16.)

**Comment by Vigilence** [comment]
I just downloaded it and will test it soon, but the node gives an error message.  Opened a separate ticket for it.
