### ISSUE TITLE
Could not detect model.

### ISSUE THREAD

**Issue by nhathoangfoto** [SeanScripts/ComfyUI-PixtralLlamaVision#4]
I have downloaded the model file and the config files within each model and placed them in their respective folders, but ComfyUI still can't recognize the models.
<img width="698" alt="image" src="https://github.com/user-attachments/assets/891cafed-3c8b-4c9f-a1ba-34a78821f8cc">

**Comment by SeanScripts** [comment]
The folder structure should be like this (using the Llama-3.2-11B-Vision-Instruct-nf4 model as an example):

`ComfyUI/models/llama-vision/Llama-3.2-11B-Vision-Instruct-nf4/model.safetensors` (and the config/tokenizer files for that model in the same folder)

So if you had other model versions/quants/finetunes you would put them inside the `llama-vision` folder, but each model still gets its own folder.

If you're using Stability Matrix, I don't think it would detect them in the shared models folder, though. I will have to figure out how to add to the model paths for that.

**Comment by SeanScripts** [comment]
No worries, I'm thinking of updating this to have them in the LLM folder anyway to be more compatible with other custom nodes.

**Comment by bramvera** [comment]
> No worries, I'm thinking of updating this to have them in the LLM folder anyway to be more compatible with other custom nodes.

thanks for this node, I play around adding Molmo and I think better than Pixtral

**Comment by SeanScripts** [comment]
Nice, I was also thinking yesterday how it would be easy to include Molmo too... Starting to think I need to rename this node set to something more general haha.

Still a little iffy about using `trust_remote_code` for Molmo, since I haven't read their code yet, but hopefully it gets added to transformers soon

**Comment by bramvera** [comment]
> Nice, I was also thinking yesterday how it would be easy to include Molmo too... Starting to think I need to rename this node set to something more general haha.
> 
> Still a little iffy about using `trust_remote_code` for Molmo, since I haven't read their code yet, but hopefully it gets added to transformers soon

yeah, I need to add trust_remote_code: True, that's why I didn't push to PR but you could take a look on my fork https://github.com/bramvera/ComfyUI-PixtralLlamaVision

**Comment by SeanScripts** [comment]
Thanks, merged your code in :)
